[package]
name = "mandelbrot-sdl2-rs"
version = "0.1.0"
authors = ["vsimoes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"
num = "0.2.0"
rayon = "1.3.0"
